import 'react-native-gesture-handler';
import React from 'react';
import {AuthProvider} from './authProvider';
import Routes from './routes';

// THIS IS THE ENTRY POINT OF THE APPLICATION
// THE ENTIRE APP IS WRAPPED AROUND THE AUTHPROVIDER COMPONENT WHICH CONTAINS ALL THE FIRESTORE DB FUNCTIONS AS A GLOBAL CONTEXT OF THE APP
// THE ROUTES COMPONENT DETERMINES WHETHER THE USER IS LOGGED IN AND THUS SHOULD BE NAVIGATED DIRECTLY TO THE MAIN APP STACK INCLUDING ALL THE MAIN COMPONENTS OF THE APP
// OR WHETHER THE USER IS NOT LOGGED IN AND SHOULD BE NAVIGATED TO THE AUTHENTICATION STACK WHICH INCLUDES THE ONBORARDING AND LOGIN SCREENS
// THIS PREVENTS THE USER FROM HAVING TO LOG IN EVERY TIME THEY OPEN THE APPLICATION

const Providers = () => {
  return (
    <AuthProvider>
      <Routes />
    </AuthProvider>
  );
};

export default Providers;
